# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from convex_plane_decomposition_msgs/PlanarRegion.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import convex_plane_decomposition_msgs.msg
import geometry_msgs.msg

class PlanarRegion(genpy.Message):
  _md5sum = "8cff8c52c8273f12e2fd17b9d4a3d417"
  _type = "convex_plane_decomposition_msgs/PlanarRegion"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """geometry_msgs/Pose plane_parameters

BoundingBox2d bbox2d

PolygonWithHoles2d boundary

PolygonWithHoles2d[] insets

================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of position and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w

================================================================================
MSG: convex_plane_decomposition_msgs/BoundingBox2d
# 3D, axis-aligned, bounding box
float32 min_x
float32 min_y
float32 max_x
float32 max_y
================================================================================
MSG: convex_plane_decomposition_msgs/PolygonWithHoles2d
# Specification of a 2D polygon with holes
Polygon2d outer_boundary
Polygon2d[] holes
================================================================================
MSG: convex_plane_decomposition_msgs/Polygon2d
# Specification of a 2D polygon where the first and last points are connected
Point2d[] points
================================================================================
MSG: convex_plane_decomposition_msgs/Point2d
float32 x
float32 y"""
  __slots__ = ['plane_parameters','bbox2d','boundary','insets']
  _slot_types = ['geometry_msgs/Pose','convex_plane_decomposition_msgs/BoundingBox2d','convex_plane_decomposition_msgs/PolygonWithHoles2d','convex_plane_decomposition_msgs/PolygonWithHoles2d[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       plane_parameters,bbox2d,boundary,insets

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(PlanarRegion, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.plane_parameters is None:
        self.plane_parameters = geometry_msgs.msg.Pose()
      if self.bbox2d is None:
        self.bbox2d = convex_plane_decomposition_msgs.msg.BoundingBox2d()
      if self.boundary is None:
        self.boundary = convex_plane_decomposition_msgs.msg.PolygonWithHoles2d()
      if self.insets is None:
        self.insets = []
    else:
      self.plane_parameters = geometry_msgs.msg.Pose()
      self.bbox2d = convex_plane_decomposition_msgs.msg.BoundingBox2d()
      self.boundary = convex_plane_decomposition_msgs.msg.PolygonWithHoles2d()
      self.insets = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_7d4f().pack(_x.plane_parameters.position.x, _x.plane_parameters.position.y, _x.plane_parameters.position.z, _x.plane_parameters.orientation.x, _x.plane_parameters.orientation.y, _x.plane_parameters.orientation.z, _x.plane_parameters.orientation.w, _x.bbox2d.min_x, _x.bbox2d.min_y, _x.bbox2d.max_x, _x.bbox2d.max_y))
      length = len(self.boundary.outer_boundary.points)
      buff.write(_struct_I.pack(length))
      for val1 in self.boundary.outer_boundary.points:
        _x = val1
        buff.write(_get_struct_2f().pack(_x.x, _x.y))
      length = len(self.boundary.holes)
      buff.write(_struct_I.pack(length))
      for val1 in self.boundary.holes:
        length = len(val1.points)
        buff.write(_struct_I.pack(length))
        for val2 in val1.points:
          _x = val2
          buff.write(_get_struct_2f().pack(_x.x, _x.y))
      length = len(self.insets)
      buff.write(_struct_I.pack(length))
      for val1 in self.insets:
        _v1 = val1.outer_boundary
        length = len(_v1.points)
        buff.write(_struct_I.pack(length))
        for val3 in _v1.points:
          _x = val3
          buff.write(_get_struct_2f().pack(_x.x, _x.y))
        length = len(val1.holes)
        buff.write(_struct_I.pack(length))
        for val2 in val1.holes:
          length = len(val2.points)
          buff.write(_struct_I.pack(length))
          for val3 in val2.points:
            _x = val3
            buff.write(_get_struct_2f().pack(_x.x, _x.y))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.plane_parameters is None:
        self.plane_parameters = geometry_msgs.msg.Pose()
      if self.bbox2d is None:
        self.bbox2d = convex_plane_decomposition_msgs.msg.BoundingBox2d()
      if self.boundary is None:
        self.boundary = convex_plane_decomposition_msgs.msg.PolygonWithHoles2d()
      if self.insets is None:
        self.insets = None
      end = 0
      _x = self
      start = end
      end += 72
      (_x.plane_parameters.position.x, _x.plane_parameters.position.y, _x.plane_parameters.position.z, _x.plane_parameters.orientation.x, _x.plane_parameters.orientation.y, _x.plane_parameters.orientation.z, _x.plane_parameters.orientation.w, _x.bbox2d.min_x, _x.bbox2d.min_y, _x.bbox2d.max_x, _x.bbox2d.max_y,) = _get_struct_7d4f().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.boundary.outer_boundary.points = []
      for i in range(0, length):
        val1 = convex_plane_decomposition_msgs.msg.Point2d()
        _x = val1
        start = end
        end += 8
        (_x.x, _x.y,) = _get_struct_2f().unpack(str[start:end])
        self.boundary.outer_boundary.points.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.boundary.holes = []
      for i in range(0, length):
        val1 = convex_plane_decomposition_msgs.msg.Polygon2d()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.points = []
        for i in range(0, length):
          val2 = convex_plane_decomposition_msgs.msg.Point2d()
          _x = val2
          start = end
          end += 8
          (_x.x, _x.y,) = _get_struct_2f().unpack(str[start:end])
          val1.points.append(val2)
        self.boundary.holes.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.insets = []
      for i in range(0, length):
        val1 = convex_plane_decomposition_msgs.msg.PolygonWithHoles2d()
        _v2 = val1.outer_boundary
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        _v2.points = []
        for i in range(0, length):
          val3 = convex_plane_decomposition_msgs.msg.Point2d()
          _x = val3
          start = end
          end += 8
          (_x.x, _x.y,) = _get_struct_2f().unpack(str[start:end])
          _v2.points.append(val3)
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.holes = []
        for i in range(0, length):
          val2 = convex_plane_decomposition_msgs.msg.Polygon2d()
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          val2.points = []
          for i in range(0, length):
            val3 = convex_plane_decomposition_msgs.msg.Point2d()
            _x = val3
            start = end
            end += 8
            (_x.x, _x.y,) = _get_struct_2f().unpack(str[start:end])
            val2.points.append(val3)
          val1.holes.append(val2)
        self.insets.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_7d4f().pack(_x.plane_parameters.position.x, _x.plane_parameters.position.y, _x.plane_parameters.position.z, _x.plane_parameters.orientation.x, _x.plane_parameters.orientation.y, _x.plane_parameters.orientation.z, _x.plane_parameters.orientation.w, _x.bbox2d.min_x, _x.bbox2d.min_y, _x.bbox2d.max_x, _x.bbox2d.max_y))
      length = len(self.boundary.outer_boundary.points)
      buff.write(_struct_I.pack(length))
      for val1 in self.boundary.outer_boundary.points:
        _x = val1
        buff.write(_get_struct_2f().pack(_x.x, _x.y))
      length = len(self.boundary.holes)
      buff.write(_struct_I.pack(length))
      for val1 in self.boundary.holes:
        length = len(val1.points)
        buff.write(_struct_I.pack(length))
        for val2 in val1.points:
          _x = val2
          buff.write(_get_struct_2f().pack(_x.x, _x.y))
      length = len(self.insets)
      buff.write(_struct_I.pack(length))
      for val1 in self.insets:
        _v3 = val1.outer_boundary
        length = len(_v3.points)
        buff.write(_struct_I.pack(length))
        for val3 in _v3.points:
          _x = val3
          buff.write(_get_struct_2f().pack(_x.x, _x.y))
        length = len(val1.holes)
        buff.write(_struct_I.pack(length))
        for val2 in val1.holes:
          length = len(val2.points)
          buff.write(_struct_I.pack(length))
          for val3 in val2.points:
            _x = val3
            buff.write(_get_struct_2f().pack(_x.x, _x.y))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.plane_parameters is None:
        self.plane_parameters = geometry_msgs.msg.Pose()
      if self.bbox2d is None:
        self.bbox2d = convex_plane_decomposition_msgs.msg.BoundingBox2d()
      if self.boundary is None:
        self.boundary = convex_plane_decomposition_msgs.msg.PolygonWithHoles2d()
      if self.insets is None:
        self.insets = None
      end = 0
      _x = self
      start = end
      end += 72
      (_x.plane_parameters.position.x, _x.plane_parameters.position.y, _x.plane_parameters.position.z, _x.plane_parameters.orientation.x, _x.plane_parameters.orientation.y, _x.plane_parameters.orientation.z, _x.plane_parameters.orientation.w, _x.bbox2d.min_x, _x.bbox2d.min_y, _x.bbox2d.max_x, _x.bbox2d.max_y,) = _get_struct_7d4f().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.boundary.outer_boundary.points = []
      for i in range(0, length):
        val1 = convex_plane_decomposition_msgs.msg.Point2d()
        _x = val1
        start = end
        end += 8
        (_x.x, _x.y,) = _get_struct_2f().unpack(str[start:end])
        self.boundary.outer_boundary.points.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.boundary.holes = []
      for i in range(0, length):
        val1 = convex_plane_decomposition_msgs.msg.Polygon2d()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.points = []
        for i in range(0, length):
          val2 = convex_plane_decomposition_msgs.msg.Point2d()
          _x = val2
          start = end
          end += 8
          (_x.x, _x.y,) = _get_struct_2f().unpack(str[start:end])
          val1.points.append(val2)
        self.boundary.holes.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.insets = []
      for i in range(0, length):
        val1 = convex_plane_decomposition_msgs.msg.PolygonWithHoles2d()
        _v4 = val1.outer_boundary
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        _v4.points = []
        for i in range(0, length):
          val3 = convex_plane_decomposition_msgs.msg.Point2d()
          _x = val3
          start = end
          end += 8
          (_x.x, _x.y,) = _get_struct_2f().unpack(str[start:end])
          _v4.points.append(val3)
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.holes = []
        for i in range(0, length):
          val2 = convex_plane_decomposition_msgs.msg.Polygon2d()
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          val2.points = []
          for i in range(0, length):
            val3 = convex_plane_decomposition_msgs.msg.Point2d()
            _x = val3
            start = end
            end += 8
            (_x.x, _x.y,) = _get_struct_2f().unpack(str[start:end])
            val2.points.append(val3)
          val1.holes.append(val2)
        self.insets.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2f = None
def _get_struct_2f():
    global _struct_2f
    if _struct_2f is None:
        _struct_2f = struct.Struct("<2f")
    return _struct_2f
_struct_7d4f = None
def _get_struct_7d4f():
    global _struct_7d4f
    if _struct_7d4f is None:
        _struct_7d4f = struct.Struct("<7d4f")
    return _struct_7d4f
