# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from convex_plane_decomposition_msgs/PlanarTerrain.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import convex_plane_decomposition_msgs.msg
import geometry_msgs.msg
import grid_map_msgs.msg
import std_msgs.msg

class PlanarTerrain(genpy.Message):
  _md5sum = "081e702fce247ef5685dd96b39e3dfd4"
  _type = "convex_plane_decomposition_msgs/PlanarTerrain"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """PlanarRegion[] planarRegions
grid_map_msgs/GridMap gridmap
================================================================================
MSG: convex_plane_decomposition_msgs/PlanarRegion
geometry_msgs/Pose plane_parameters

BoundingBox2d bbox2d

PolygonWithHoles2d boundary

PolygonWithHoles2d[] insets

================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of position and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w

================================================================================
MSG: convex_plane_decomposition_msgs/BoundingBox2d
# 3D, axis-aligned, bounding box
float32 min_x
float32 min_y
float32 max_x
float32 max_y
================================================================================
MSG: convex_plane_decomposition_msgs/PolygonWithHoles2d
# Specification of a 2D polygon with holes
Polygon2d outer_boundary
Polygon2d[] holes
================================================================================
MSG: convex_plane_decomposition_msgs/Polygon2d
# Specification of a 2D polygon where the first and last points are connected
Point2d[] points
================================================================================
MSG: convex_plane_decomposition_msgs/Point2d
float32 x
float32 y
================================================================================
MSG: grid_map_msgs/GridMap
# Grid map header
GridMapInfo info

# Grid map layer names.
string[] layers

# Grid map basic layer names (optional). The basic layers
# determine which layers from `layers` need to be valid
# in order for a cell of the grid map to be valid.
string[] basic_layers

# Grid map data.
std_msgs/Float32MultiArray[] data

# Row start index (default 0).
uint16 outer_start_index

# Column start index (default 0).
uint16 inner_start_index

================================================================================
MSG: grid_map_msgs/GridMapInfo
# Header (time and frame)
Header header

# Resolution of the grid [m/cell].
float64 resolution

# Length in x-direction [m].
float64 length_x

# Length in y-direction [m].
float64 length_y

# Pose of the grid map center in the frame defined in `header` [m].
geometry_msgs/Pose pose
================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: std_msgs/Float32MultiArray
# Please look at the MultiArrayLayout message definition for
# documentation on all multiarrays.

MultiArrayLayout  layout        # specification of data layout
float32[]         data          # array of data


================================================================================
MSG: std_msgs/MultiArrayLayout
# The multiarray declares a generic multi-dimensional array of a
# particular data type.  Dimensions are ordered from outer most
# to inner most.

MultiArrayDimension[] dim # Array of dimension properties
uint32 data_offset        # padding elements at front of data

# Accessors should ALWAYS be written in terms of dimension stride
# and specified outer-most dimension first.
# 
# multiarray(i,j,k) = data[data_offset + dim_stride[1]*i + dim_stride[2]*j + k]
#
# A standard, 3-channel 640x480 image with interleaved color channels
# would be specified as:
#
# dim[0].label  = "height"
# dim[0].size   = 480
# dim[0].stride = 3*640*480 = 921600  (note dim[0] stride is just size of image)
# dim[1].label  = "width"
# dim[1].size   = 640
# dim[1].stride = 3*640 = 1920
# dim[2].label  = "channel"
# dim[2].size   = 3
# dim[2].stride = 3
#
# multiarray(i,j,k) refers to the ith row, jth column, and kth channel.

================================================================================
MSG: std_msgs/MultiArrayDimension
string label   # label of given dimension
uint32 size    # size of given dimension (in type units)
uint32 stride  # stride of given dimension"""
  __slots__ = ['planarRegions','gridmap']
  _slot_types = ['convex_plane_decomposition_msgs/PlanarRegion[]','grid_map_msgs/GridMap']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       planarRegions,gridmap

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(PlanarTerrain, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.planarRegions is None:
        self.planarRegions = []
      if self.gridmap is None:
        self.gridmap = grid_map_msgs.msg.GridMap()
    else:
      self.planarRegions = []
      self.gridmap = grid_map_msgs.msg.GridMap()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.planarRegions)
      buff.write(_struct_I.pack(length))
      for val1 in self.planarRegions:
        _v1 = val1.plane_parameters
        _v2 = _v1.position
        _x = _v2
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v3 = _v1.orientation
        _x = _v3
        buff.write(_get_struct_4d().pack(_x.x, _x.y, _x.z, _x.w))
        _v4 = val1.bbox2d
        _x = _v4
        buff.write(_get_struct_4f().pack(_x.min_x, _x.min_y, _x.max_x, _x.max_y))
        _v5 = val1.boundary
        _v6 = _v5.outer_boundary
        length = len(_v6.points)
        buff.write(_struct_I.pack(length))
        for val4 in _v6.points:
          _x = val4
          buff.write(_get_struct_2f().pack(_x.x, _x.y))
        length = len(_v5.holes)
        buff.write(_struct_I.pack(length))
        for val3 in _v5.holes:
          length = len(val3.points)
          buff.write(_struct_I.pack(length))
          for val4 in val3.points:
            _x = val4
            buff.write(_get_struct_2f().pack(_x.x, _x.y))
        length = len(val1.insets)
        buff.write(_struct_I.pack(length))
        for val2 in val1.insets:
          _v7 = val2.outer_boundary
          length = len(_v7.points)
          buff.write(_struct_I.pack(length))
          for val4 in _v7.points:
            _x = val4
            buff.write(_get_struct_2f().pack(_x.x, _x.y))
          length = len(val2.holes)
          buff.write(_struct_I.pack(length))
          for val3 in val2.holes:
            length = len(val3.points)
            buff.write(_struct_I.pack(length))
            for val4 in val3.points:
              _x = val4
              buff.write(_get_struct_2f().pack(_x.x, _x.y))
      _x = self
      buff.write(_get_struct_3I().pack(_x.gridmap.info.header.seq, _x.gridmap.info.header.stamp.secs, _x.gridmap.info.header.stamp.nsecs))
      _x = self.gridmap.info.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_10d().pack(_x.gridmap.info.resolution, _x.gridmap.info.length_x, _x.gridmap.info.length_y, _x.gridmap.info.pose.position.x, _x.gridmap.info.pose.position.y, _x.gridmap.info.pose.position.z, _x.gridmap.info.pose.orientation.x, _x.gridmap.info.pose.orientation.y, _x.gridmap.info.pose.orientation.z, _x.gridmap.info.pose.orientation.w))
      length = len(self.gridmap.layers)
      buff.write(_struct_I.pack(length))
      for val1 in self.gridmap.layers:
        length = len(val1)
        if python3 or type(val1) == unicode:
          val1 = val1.encode('utf-8')
          length = len(val1)
        buff.write(struct.Struct('<I%ss'%length).pack(length, val1))
      length = len(self.gridmap.basic_layers)
      buff.write(_struct_I.pack(length))
      for val1 in self.gridmap.basic_layers:
        length = len(val1)
        if python3 or type(val1) == unicode:
          val1 = val1.encode('utf-8')
          length = len(val1)
        buff.write(struct.Struct('<I%ss'%length).pack(length, val1))
      length = len(self.gridmap.data)
      buff.write(_struct_I.pack(length))
      for val1 in self.gridmap.data:
        _v8 = val1.layout
        length = len(_v8.dim)
        buff.write(_struct_I.pack(length))
        for val3 in _v8.dim:
          _x = val3.label
          length = len(_x)
          if python3 or type(_x) == unicode:
            _x = _x.encode('utf-8')
            length = len(_x)
          buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
          _x = val3
          buff.write(_get_struct_2I().pack(_x.size, _x.stride))
        _x = _v8.data_offset
        buff.write(_get_struct_I().pack(_x))
        length = len(val1.data)
        buff.write(_struct_I.pack(length))
        pattern = '<%sf'%length
        buff.write(struct.Struct(pattern).pack(*val1.data))
      _x = self
      buff.write(_get_struct_2H().pack(_x.gridmap.outer_start_index, _x.gridmap.inner_start_index))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.planarRegions is None:
        self.planarRegions = None
      if self.gridmap is None:
        self.gridmap = grid_map_msgs.msg.GridMap()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.planarRegions = []
      for i in range(0, length):
        val1 = convex_plane_decomposition_msgs.msg.PlanarRegion()
        _v9 = val1.plane_parameters
        _v10 = _v9.position
        _x = _v10
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v11 = _v9.orientation
        _x = _v11
        start = end
        end += 32
        (_x.x, _x.y, _x.z, _x.w,) = _get_struct_4d().unpack(str[start:end])
        _v12 = val1.bbox2d
        _x = _v12
        start = end
        end += 16
        (_x.min_x, _x.min_y, _x.max_x, _x.max_y,) = _get_struct_4f().unpack(str[start:end])
        _v13 = val1.boundary
        _v14 = _v13.outer_boundary
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        _v14.points = []
        for i in range(0, length):
          val4 = convex_plane_decomposition_msgs.msg.Point2d()
          _x = val4
          start = end
          end += 8
          (_x.x, _x.y,) = _get_struct_2f().unpack(str[start:end])
          _v14.points.append(val4)
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        _v13.holes = []
        for i in range(0, length):
          val3 = convex_plane_decomposition_msgs.msg.Polygon2d()
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          val3.points = []
          for i in range(0, length):
            val4 = convex_plane_decomposition_msgs.msg.Point2d()
            _x = val4
            start = end
            end += 8
            (_x.x, _x.y,) = _get_struct_2f().unpack(str[start:end])
            val3.points.append(val4)
          _v13.holes.append(val3)
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.insets = []
        for i in range(0, length):
          val2 = convex_plane_decomposition_msgs.msg.PolygonWithHoles2d()
          _v15 = val2.outer_boundary
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          _v15.points = []
          for i in range(0, length):
            val4 = convex_plane_decomposition_msgs.msg.Point2d()
            _x = val4
            start = end
            end += 8
            (_x.x, _x.y,) = _get_struct_2f().unpack(str[start:end])
            _v15.points.append(val4)
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          val2.holes = []
          for i in range(0, length):
            val3 = convex_plane_decomposition_msgs.msg.Polygon2d()
            start = end
            end += 4
            (length,) = _struct_I.unpack(str[start:end])
            val3.points = []
            for i in range(0, length):
              val4 = convex_plane_decomposition_msgs.msg.Point2d()
              _x = val4
              start = end
              end += 8
              (_x.x, _x.y,) = _get_struct_2f().unpack(str[start:end])
              val3.points.append(val4)
            val2.holes.append(val3)
          val1.insets.append(val2)
        self.planarRegions.append(val1)
      _x = self
      start = end
      end += 12
      (_x.gridmap.info.header.seq, _x.gridmap.info.header.stamp.secs, _x.gridmap.info.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.gridmap.info.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.gridmap.info.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 80
      (_x.gridmap.info.resolution, _x.gridmap.info.length_x, _x.gridmap.info.length_y, _x.gridmap.info.pose.position.x, _x.gridmap.info.pose.position.y, _x.gridmap.info.pose.position.z, _x.gridmap.info.pose.orientation.x, _x.gridmap.info.pose.orientation.y, _x.gridmap.info.pose.orientation.z, _x.gridmap.info.pose.orientation.w,) = _get_struct_10d().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.gridmap.layers = []
      for i in range(0, length):
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1 = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1 = str[start:end]
        self.gridmap.layers.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.gridmap.basic_layers = []
      for i in range(0, length):
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1 = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1 = str[start:end]
        self.gridmap.basic_layers.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.gridmap.data = []
      for i in range(0, length):
        val1 = std_msgs.msg.Float32MultiArray()
        _v16 = val1.layout
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        _v16.dim = []
        for i in range(0, length):
          val3 = std_msgs.msg.MultiArrayDimension()
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          start = end
          end += length
          if python3:
            val3.label = str[start:end].decode('utf-8', 'rosmsg')
          else:
            val3.label = str[start:end]
          _x = val3
          start = end
          end += 8
          (_x.size, _x.stride,) = _get_struct_2I().unpack(str[start:end])
          _v16.dim.append(val3)
        start = end
        end += 4
        (_v16.data_offset,) = _get_struct_I().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        pattern = '<%sf'%length
        start = end
        s = struct.Struct(pattern)
        end += s.size
        val1.data = s.unpack(str[start:end])
        self.gridmap.data.append(val1)
      _x = self
      start = end
      end += 4
      (_x.gridmap.outer_start_index, _x.gridmap.inner_start_index,) = _get_struct_2H().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.planarRegions)
      buff.write(_struct_I.pack(length))
      for val1 in self.planarRegions:
        _v17 = val1.plane_parameters
        _v18 = _v17.position
        _x = _v18
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v19 = _v17.orientation
        _x = _v19
        buff.write(_get_struct_4d().pack(_x.x, _x.y, _x.z, _x.w))
        _v20 = val1.bbox2d
        _x = _v20
        buff.write(_get_struct_4f().pack(_x.min_x, _x.min_y, _x.max_x, _x.max_y))
        _v21 = val1.boundary
        _v22 = _v21.outer_boundary
        length = len(_v22.points)
        buff.write(_struct_I.pack(length))
        for val4 in _v22.points:
          _x = val4
          buff.write(_get_struct_2f().pack(_x.x, _x.y))
        length = len(_v21.holes)
        buff.write(_struct_I.pack(length))
        for val3 in _v21.holes:
          length = len(val3.points)
          buff.write(_struct_I.pack(length))
          for val4 in val3.points:
            _x = val4
            buff.write(_get_struct_2f().pack(_x.x, _x.y))
        length = len(val1.insets)
        buff.write(_struct_I.pack(length))
        for val2 in val1.insets:
          _v23 = val2.outer_boundary
          length = len(_v23.points)
          buff.write(_struct_I.pack(length))
          for val4 in _v23.points:
            _x = val4
            buff.write(_get_struct_2f().pack(_x.x, _x.y))
          length = len(val2.holes)
          buff.write(_struct_I.pack(length))
          for val3 in val2.holes:
            length = len(val3.points)
            buff.write(_struct_I.pack(length))
            for val4 in val3.points:
              _x = val4
              buff.write(_get_struct_2f().pack(_x.x, _x.y))
      _x = self
      buff.write(_get_struct_3I().pack(_x.gridmap.info.header.seq, _x.gridmap.info.header.stamp.secs, _x.gridmap.info.header.stamp.nsecs))
      _x = self.gridmap.info.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_10d().pack(_x.gridmap.info.resolution, _x.gridmap.info.length_x, _x.gridmap.info.length_y, _x.gridmap.info.pose.position.x, _x.gridmap.info.pose.position.y, _x.gridmap.info.pose.position.z, _x.gridmap.info.pose.orientation.x, _x.gridmap.info.pose.orientation.y, _x.gridmap.info.pose.orientation.z, _x.gridmap.info.pose.orientation.w))
      length = len(self.gridmap.layers)
      buff.write(_struct_I.pack(length))
      for val1 in self.gridmap.layers:
        length = len(val1)
        if python3 or type(val1) == unicode:
          val1 = val1.encode('utf-8')
          length = len(val1)
        buff.write(struct.Struct('<I%ss'%length).pack(length, val1))
      length = len(self.gridmap.basic_layers)
      buff.write(_struct_I.pack(length))
      for val1 in self.gridmap.basic_layers:
        length = len(val1)
        if python3 or type(val1) == unicode:
          val1 = val1.encode('utf-8')
          length = len(val1)
        buff.write(struct.Struct('<I%ss'%length).pack(length, val1))
      length = len(self.gridmap.data)
      buff.write(_struct_I.pack(length))
      for val1 in self.gridmap.data:
        _v24 = val1.layout
        length = len(_v24.dim)
        buff.write(_struct_I.pack(length))
        for val3 in _v24.dim:
          _x = val3.label
          length = len(_x)
          if python3 or type(_x) == unicode:
            _x = _x.encode('utf-8')
            length = len(_x)
          buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
          _x = val3
          buff.write(_get_struct_2I().pack(_x.size, _x.stride))
        _x = _v24.data_offset
        buff.write(_get_struct_I().pack(_x))
        length = len(val1.data)
        buff.write(_struct_I.pack(length))
        pattern = '<%sf'%length
        buff.write(val1.data.tostring())
      _x = self
      buff.write(_get_struct_2H().pack(_x.gridmap.outer_start_index, _x.gridmap.inner_start_index))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.planarRegions is None:
        self.planarRegions = None
      if self.gridmap is None:
        self.gridmap = grid_map_msgs.msg.GridMap()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.planarRegions = []
      for i in range(0, length):
        val1 = convex_plane_decomposition_msgs.msg.PlanarRegion()
        _v25 = val1.plane_parameters
        _v26 = _v25.position
        _x = _v26
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v27 = _v25.orientation
        _x = _v27
        start = end
        end += 32
        (_x.x, _x.y, _x.z, _x.w,) = _get_struct_4d().unpack(str[start:end])
        _v28 = val1.bbox2d
        _x = _v28
        start = end
        end += 16
        (_x.min_x, _x.min_y, _x.max_x, _x.max_y,) = _get_struct_4f().unpack(str[start:end])
        _v29 = val1.boundary
        _v30 = _v29.outer_boundary
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        _v30.points = []
        for i in range(0, length):
          val4 = convex_plane_decomposition_msgs.msg.Point2d()
          _x = val4
          start = end
          end += 8
          (_x.x, _x.y,) = _get_struct_2f().unpack(str[start:end])
          _v30.points.append(val4)
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        _v29.holes = []
        for i in range(0, length):
          val3 = convex_plane_decomposition_msgs.msg.Polygon2d()
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          val3.points = []
          for i in range(0, length):
            val4 = convex_plane_decomposition_msgs.msg.Point2d()
            _x = val4
            start = end
            end += 8
            (_x.x, _x.y,) = _get_struct_2f().unpack(str[start:end])
            val3.points.append(val4)
          _v29.holes.append(val3)
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.insets = []
        for i in range(0, length):
          val2 = convex_plane_decomposition_msgs.msg.PolygonWithHoles2d()
          _v31 = val2.outer_boundary
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          _v31.points = []
          for i in range(0, length):
            val4 = convex_plane_decomposition_msgs.msg.Point2d()
            _x = val4
            start = end
            end += 8
            (_x.x, _x.y,) = _get_struct_2f().unpack(str[start:end])
            _v31.points.append(val4)
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          val2.holes = []
          for i in range(0, length):
            val3 = convex_plane_decomposition_msgs.msg.Polygon2d()
            start = end
            end += 4
            (length,) = _struct_I.unpack(str[start:end])
            val3.points = []
            for i in range(0, length):
              val4 = convex_plane_decomposition_msgs.msg.Point2d()
              _x = val4
              start = end
              end += 8
              (_x.x, _x.y,) = _get_struct_2f().unpack(str[start:end])
              val3.points.append(val4)
            val2.holes.append(val3)
          val1.insets.append(val2)
        self.planarRegions.append(val1)
      _x = self
      start = end
      end += 12
      (_x.gridmap.info.header.seq, _x.gridmap.info.header.stamp.secs, _x.gridmap.info.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.gridmap.info.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.gridmap.info.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 80
      (_x.gridmap.info.resolution, _x.gridmap.info.length_x, _x.gridmap.info.length_y, _x.gridmap.info.pose.position.x, _x.gridmap.info.pose.position.y, _x.gridmap.info.pose.position.z, _x.gridmap.info.pose.orientation.x, _x.gridmap.info.pose.orientation.y, _x.gridmap.info.pose.orientation.z, _x.gridmap.info.pose.orientation.w,) = _get_struct_10d().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.gridmap.layers = []
      for i in range(0, length):
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1 = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1 = str[start:end]
        self.gridmap.layers.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.gridmap.basic_layers = []
      for i in range(0, length):
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1 = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1 = str[start:end]
        self.gridmap.basic_layers.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.gridmap.data = []
      for i in range(0, length):
        val1 = std_msgs.msg.Float32MultiArray()
        _v32 = val1.layout
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        _v32.dim = []
        for i in range(0, length):
          val3 = std_msgs.msg.MultiArrayDimension()
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          start = end
          end += length
          if python3:
            val3.label = str[start:end].decode('utf-8', 'rosmsg')
          else:
            val3.label = str[start:end]
          _x = val3
          start = end
          end += 8
          (_x.size, _x.stride,) = _get_struct_2I().unpack(str[start:end])
          _v32.dim.append(val3)
        start = end
        end += 4
        (_v32.data_offset,) = _get_struct_I().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        pattern = '<%sf'%length
        start = end
        s = struct.Struct(pattern)
        end += s.size
        val1.data = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
        self.gridmap.data.append(val1)
      _x = self
      start = end
      end += 4
      (_x.gridmap.outer_start_index, _x.gridmap.inner_start_index,) = _get_struct_2H().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_10d = None
def _get_struct_10d():
    global _struct_10d
    if _struct_10d is None:
        _struct_10d = struct.Struct("<10d")
    return _struct_10d
_struct_2H = None
def _get_struct_2H():
    global _struct_2H
    if _struct_2H is None:
        _struct_2H = struct.Struct("<2H")
    return _struct_2H
_struct_2I = None
def _get_struct_2I():
    global _struct_2I
    if _struct_2I is None:
        _struct_2I = struct.Struct("<2I")
    return _struct_2I
_struct_2f = None
def _get_struct_2f():
    global _struct_2f
    if _struct_2f is None:
        _struct_2f = struct.Struct("<2f")
    return _struct_2f
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_3d = None
def _get_struct_3d():
    global _struct_3d
    if _struct_3d is None:
        _struct_3d = struct.Struct("<3d")
    return _struct_3d
_struct_4d = None
def _get_struct_4d():
    global _struct_4d
    if _struct_4d is None:
        _struct_4d = struct.Struct("<4d")
    return _struct_4d
_struct_4f = None
def _get_struct_4f():
    global _struct_4f
    if _struct_4f is None:
        _struct_4f = struct.Struct("<4f")
    return _struct_4f
