# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from convex_plane_decomposition_msgs/PolygonWithHoles2d.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import convex_plane_decomposition_msgs.msg

class PolygonWithHoles2d(genpy.Message):
  _md5sum = "62e09666eefc245f9ca3347875cb36cc"
  _type = "convex_plane_decomposition_msgs/PolygonWithHoles2d"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# Specification of a 2D polygon with holes
Polygon2d outer_boundary
Polygon2d[] holes
================================================================================
MSG: convex_plane_decomposition_msgs/Polygon2d
# Specification of a 2D polygon where the first and last points are connected
Point2d[] points
================================================================================
MSG: convex_plane_decomposition_msgs/Point2d
float32 x
float32 y"""
  __slots__ = ['outer_boundary','holes']
  _slot_types = ['convex_plane_decomposition_msgs/Polygon2d','convex_plane_decomposition_msgs/Polygon2d[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       outer_boundary,holes

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(PolygonWithHoles2d, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.outer_boundary is None:
        self.outer_boundary = convex_plane_decomposition_msgs.msg.Polygon2d()
      if self.holes is None:
        self.holes = []
    else:
      self.outer_boundary = convex_plane_decomposition_msgs.msg.Polygon2d()
      self.holes = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.outer_boundary.points)
      buff.write(_struct_I.pack(length))
      for val1 in self.outer_boundary.points:
        _x = val1
        buff.write(_get_struct_2f().pack(_x.x, _x.y))
      length = len(self.holes)
      buff.write(_struct_I.pack(length))
      for val1 in self.holes:
        length = len(val1.points)
        buff.write(_struct_I.pack(length))
        for val2 in val1.points:
          _x = val2
          buff.write(_get_struct_2f().pack(_x.x, _x.y))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.outer_boundary is None:
        self.outer_boundary = convex_plane_decomposition_msgs.msg.Polygon2d()
      if self.holes is None:
        self.holes = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.outer_boundary.points = []
      for i in range(0, length):
        val1 = convex_plane_decomposition_msgs.msg.Point2d()
        _x = val1
        start = end
        end += 8
        (_x.x, _x.y,) = _get_struct_2f().unpack(str[start:end])
        self.outer_boundary.points.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.holes = []
      for i in range(0, length):
        val1 = convex_plane_decomposition_msgs.msg.Polygon2d()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.points = []
        for i in range(0, length):
          val2 = convex_plane_decomposition_msgs.msg.Point2d()
          _x = val2
          start = end
          end += 8
          (_x.x, _x.y,) = _get_struct_2f().unpack(str[start:end])
          val1.points.append(val2)
        self.holes.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.outer_boundary.points)
      buff.write(_struct_I.pack(length))
      for val1 in self.outer_boundary.points:
        _x = val1
        buff.write(_get_struct_2f().pack(_x.x, _x.y))
      length = len(self.holes)
      buff.write(_struct_I.pack(length))
      for val1 in self.holes:
        length = len(val1.points)
        buff.write(_struct_I.pack(length))
        for val2 in val1.points:
          _x = val2
          buff.write(_get_struct_2f().pack(_x.x, _x.y))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.outer_boundary is None:
        self.outer_boundary = convex_plane_decomposition_msgs.msg.Polygon2d()
      if self.holes is None:
        self.holes = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.outer_boundary.points = []
      for i in range(0, length):
        val1 = convex_plane_decomposition_msgs.msg.Point2d()
        _x = val1
        start = end
        end += 8
        (_x.x, _x.y,) = _get_struct_2f().unpack(str[start:end])
        self.outer_boundary.points.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.holes = []
      for i in range(0, length):
        val1 = convex_plane_decomposition_msgs.msg.Polygon2d()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.points = []
        for i in range(0, length):
          val2 = convex_plane_decomposition_msgs.msg.Point2d()
          _x = val2
          start = end
          end += 8
          (_x.x, _x.y,) = _get_struct_2f().unpack(str[start:end])
          val1.points.append(val2)
        self.holes.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2f = None
def _get_struct_2f():
    global _struct_2f
    if _struct_2f is None:
        _struct_2f = struct.Struct("<2f")
    return _struct_2f
