(cl:defpackage elevation_map_msgs-srv
  (:use )
  (:export
   "CHECKSAFETY"
   "<CHECKSAFETY-REQUEST>"
   "CHECKSAFETY-REQUEST"
   "<CHECKSAFETY-RESPONSE>"
   "CHECKSAFETY-RESPONSE"
   "INITIALIZE"
   "<INITIALIZE-REQUEST>"
   "INITIALIZE-REQUEST"
   "<INITIALIZE-RESPONSE>"
   "INITIALIZE-RESPONSE"
  ))

