// Generated by gencpp from file elevation_map_msgs/ChannelInfo.msg
// DO NOT EDIT!


#ifndef ELEVATION_MAP_MSGS_MESSAGE_CHANNELINFO_H
#define ELEVATION_MAP_MSGS_MESSAGE_CHANNELINFO_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace elevation_map_msgs
{
template <class ContainerAllocator>
struct ChannelInfo_
{
  typedef ChannelInfo_<ContainerAllocator> Type;

  ChannelInfo_()
    : header()
    , channels()  {
    }
  ChannelInfo_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , channels(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>> _channels_type;
  _channels_type channels;





  typedef boost::shared_ptr< ::elevation_map_msgs::ChannelInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::elevation_map_msgs::ChannelInfo_<ContainerAllocator> const> ConstPtr;

}; // struct ChannelInfo_

typedef ::elevation_map_msgs::ChannelInfo_<std::allocator<void> > ChannelInfo;

typedef boost::shared_ptr< ::elevation_map_msgs::ChannelInfo > ChannelInfoPtr;
typedef boost::shared_ptr< ::elevation_map_msgs::ChannelInfo const> ChannelInfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::elevation_map_msgs::ChannelInfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::elevation_map_msgs::ChannelInfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::elevation_map_msgs::ChannelInfo_<ContainerAllocator1> & lhs, const ::elevation_map_msgs::ChannelInfo_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.channels == rhs.channels;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::elevation_map_msgs::ChannelInfo_<ContainerAllocator1> & lhs, const ::elevation_map_msgs::ChannelInfo_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace elevation_map_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::elevation_map_msgs::ChannelInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::elevation_map_msgs::ChannelInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::elevation_map_msgs::ChannelInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::elevation_map_msgs::ChannelInfo_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::elevation_map_msgs::ChannelInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::elevation_map_msgs::ChannelInfo_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::elevation_map_msgs::ChannelInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3486d52fe9f3586d814c3408f751762e";
  }

  static const char* value(const ::elevation_map_msgs::ChannelInfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3486d52fe9f3586dULL;
  static const uint64_t static_value2 = 0x814c3408f751762eULL;
};

template<class ContainerAllocator>
struct DataType< ::elevation_map_msgs::ChannelInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "elevation_map_msgs/ChannelInfo";
  }

  static const char* value(const ::elevation_map_msgs::ChannelInfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::elevation_map_msgs::ChannelInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"string[] channels       # channel names for each layer\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::elevation_map_msgs::ChannelInfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::elevation_map_msgs::ChannelInfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.channels);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ChannelInfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::elevation_map_msgs::ChannelInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::elevation_map_msgs::ChannelInfo_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "channels: ";
    if (v.channels.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.channels.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, true ? std::string() : indent + "    ", v.channels[i]);
    }
    if (v.channels.empty() || true)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // ELEVATION_MAP_MSGS_MESSAGE_CHANNELINFO_H
