// Generated by gencpp from file elevation_map_msgs/CheckSafetyRequest.msg
// DO NOT EDIT!


#ifndef ELEVATION_MAP_MSGS_MESSAGE_CHECKSAFETYREQUEST_H
#define ELEVATION_MAP_MSGS_MESSAGE_CHECKSAFETYREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PolygonStamped.h>

namespace elevation_map_msgs
{
template <class ContainerAllocator>
struct CheckSafetyRequest_
{
  typedef CheckSafetyRequest_<ContainerAllocator> Type;

  CheckSafetyRequest_()
    : polygons()
    , compute_untraversable_polygon(false)  {
    }
  CheckSafetyRequest_(const ContainerAllocator& _alloc)
    : polygons(_alloc)
    , compute_untraversable_polygon(false)  {
  (void)_alloc;
    }



   typedef std::vector< ::geometry_msgs::PolygonStamped_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::PolygonStamped_<ContainerAllocator> >> _polygons_type;
  _polygons_type polygons;

   typedef uint8_t _compute_untraversable_polygon_type;
  _compute_untraversable_polygon_type compute_untraversable_polygon;





  typedef boost::shared_ptr< ::elevation_map_msgs::CheckSafetyRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::elevation_map_msgs::CheckSafetyRequest_<ContainerAllocator> const> ConstPtr;

}; // struct CheckSafetyRequest_

typedef ::elevation_map_msgs::CheckSafetyRequest_<std::allocator<void> > CheckSafetyRequest;

typedef boost::shared_ptr< ::elevation_map_msgs::CheckSafetyRequest > CheckSafetyRequestPtr;
typedef boost::shared_ptr< ::elevation_map_msgs::CheckSafetyRequest const> CheckSafetyRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::elevation_map_msgs::CheckSafetyRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::elevation_map_msgs::CheckSafetyRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::elevation_map_msgs::CheckSafetyRequest_<ContainerAllocator1> & lhs, const ::elevation_map_msgs::CheckSafetyRequest_<ContainerAllocator2> & rhs)
{
  return lhs.polygons == rhs.polygons &&
    lhs.compute_untraversable_polygon == rhs.compute_untraversable_polygon;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::elevation_map_msgs::CheckSafetyRequest_<ContainerAllocator1> & lhs, const ::elevation_map_msgs::CheckSafetyRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace elevation_map_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::elevation_map_msgs::CheckSafetyRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::elevation_map_msgs::CheckSafetyRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::elevation_map_msgs::CheckSafetyRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::elevation_map_msgs::CheckSafetyRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::elevation_map_msgs::CheckSafetyRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::elevation_map_msgs::CheckSafetyRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::elevation_map_msgs::CheckSafetyRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7259452fd835a6852d543d6eec938e47";
  }

  static const char* value(const ::elevation_map_msgs::CheckSafetyRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7259452fd835a685ULL;
  static const uint64_t static_value2 = 0x2d543d6eec938e47ULL;
};

template<class ContainerAllocator>
struct DataType< ::elevation_map_msgs::CheckSafetyRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "elevation_map_msgs/CheckSafetyRequest";
  }

  static const char* value(const ::elevation_map_msgs::CheckSafetyRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::elevation_map_msgs::CheckSafetyRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Polygons to check\n"
"geometry_msgs/PolygonStamped[] polygons\n"
"bool compute_untraversable_polygon\n"
"\n"
"# Results\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PolygonStamped\n"
"# This represents a Polygon with reference coordinate frame and timestamp\n"
"Header header\n"
"Polygon polygon\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Polygon\n"
"#A specification of a polygon where the first and last points are assumed to be connected\n"
"Point32[] points\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point32\n"
"# This contains the position of a point in free space(with 32 bits of precision).\n"
"# It is recommeded to use Point wherever possible instead of Point32.  \n"
"# \n"
"# This recommendation is to promote interoperability.  \n"
"#\n"
"# This message is designed to take up less space when sending\n"
"# lots of points at once, as in the case of a PointCloud.  \n"
"\n"
"float32 x\n"
"float32 y\n"
"float32 z\n"
;
  }

  static const char* value(const ::elevation_map_msgs::CheckSafetyRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::elevation_map_msgs::CheckSafetyRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.polygons);
      stream.next(m.compute_untraversable_polygon);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CheckSafetyRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::elevation_map_msgs::CheckSafetyRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::elevation_map_msgs::CheckSafetyRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "polygons: ";
    if (v.polygons.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.polygons.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::geometry_msgs::PolygonStamped_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.polygons[i]);
    }
    if (v.polygons.empty() || false)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "compute_untraversable_polygon: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.compute_untraversable_polygon);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ELEVATION_MAP_MSGS_MESSAGE_CHECKSAFETYREQUEST_H
