// Generated by gencpp from file elevation_map_msgs/CheckSafetyResponse.msg
// DO NOT EDIT!


#ifndef ELEVATION_MAP_MSGS_MESSAGE_CHECKSAFETYRESPONSE_H
#define ELEVATION_MAP_MSGS_MESSAGE_CHECKSAFETYRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PolygonStamped.h>

namespace elevation_map_msgs
{
template <class ContainerAllocator>
struct CheckSafetyResponse_
{
  typedef CheckSafetyResponse_<ContainerAllocator> Type;

  CheckSafetyResponse_()
    : is_safe()
    , traversability()
    , untraversable_polygons()  {
    }
  CheckSafetyResponse_(const ContainerAllocator& _alloc)
    : is_safe(_alloc)
    , traversability(_alloc)
    , untraversable_polygons(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<uint8_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint8_t>> _is_safe_type;
  _is_safe_type is_safe;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _traversability_type;
  _traversability_type traversability;

   typedef std::vector< ::geometry_msgs::PolygonStamped_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::PolygonStamped_<ContainerAllocator> >> _untraversable_polygons_type;
  _untraversable_polygons_type untraversable_polygons;





  typedef boost::shared_ptr< ::elevation_map_msgs::CheckSafetyResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::elevation_map_msgs::CheckSafetyResponse_<ContainerAllocator> const> ConstPtr;

}; // struct CheckSafetyResponse_

typedef ::elevation_map_msgs::CheckSafetyResponse_<std::allocator<void> > CheckSafetyResponse;

typedef boost::shared_ptr< ::elevation_map_msgs::CheckSafetyResponse > CheckSafetyResponsePtr;
typedef boost::shared_ptr< ::elevation_map_msgs::CheckSafetyResponse const> CheckSafetyResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::elevation_map_msgs::CheckSafetyResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::elevation_map_msgs::CheckSafetyResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::elevation_map_msgs::CheckSafetyResponse_<ContainerAllocator1> & lhs, const ::elevation_map_msgs::CheckSafetyResponse_<ContainerAllocator2> & rhs)
{
  return lhs.is_safe == rhs.is_safe &&
    lhs.traversability == rhs.traversability &&
    lhs.untraversable_polygons == rhs.untraversable_polygons;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::elevation_map_msgs::CheckSafetyResponse_<ContainerAllocator1> & lhs, const ::elevation_map_msgs::CheckSafetyResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace elevation_map_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::elevation_map_msgs::CheckSafetyResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::elevation_map_msgs::CheckSafetyResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::elevation_map_msgs::CheckSafetyResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::elevation_map_msgs::CheckSafetyResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::elevation_map_msgs::CheckSafetyResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::elevation_map_msgs::CheckSafetyResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::elevation_map_msgs::CheckSafetyResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "beb1ac95aeeddf0ee9cd130e4e05c9d0";
  }

  static const char* value(const ::elevation_map_msgs::CheckSafetyResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbeb1ac95aeeddf0eULL;
  static const uint64_t static_value2 = 0xe9cd130e4e05c9d0ULL;
};

template<class ContainerAllocator>
struct DataType< ::elevation_map_msgs::CheckSafetyResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "elevation_map_msgs/CheckSafetyResponse";
  }

  static const char* value(const ::elevation_map_msgs::CheckSafetyResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::elevation_map_msgs::CheckSafetyResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool[] is_safe\n"
"\n"
"# Estimate of the traversability of the path.\n"
"# Ranges from 0 to 1 where 0 means not traversable and 1 highly traversable.\n"
"float64[] traversability\n"
"\n"
"# Polygons that are untraversable.\n"
"geometry_msgs/PolygonStamped[] untraversable_polygons\n"
"\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PolygonStamped\n"
"# This represents a Polygon with reference coordinate frame and timestamp\n"
"Header header\n"
"Polygon polygon\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Polygon\n"
"#A specification of a polygon where the first and last points are assumed to be connected\n"
"Point32[] points\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point32\n"
"# This contains the position of a point in free space(with 32 bits of precision).\n"
"# It is recommeded to use Point wherever possible instead of Point32.  \n"
"# \n"
"# This recommendation is to promote interoperability.  \n"
"#\n"
"# This message is designed to take up less space when sending\n"
"# lots of points at once, as in the case of a PointCloud.  \n"
"\n"
"float32 x\n"
"float32 y\n"
"float32 z\n"
;
  }

  static const char* value(const ::elevation_map_msgs::CheckSafetyResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::elevation_map_msgs::CheckSafetyResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.is_safe);
      stream.next(m.traversability);
      stream.next(m.untraversable_polygons);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CheckSafetyResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::elevation_map_msgs::CheckSafetyResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::elevation_map_msgs::CheckSafetyResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "is_safe: ";
    if (v.is_safe.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.is_safe.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<uint8_t>::stream(s, true ? std::string() : indent + "    ", v.is_safe[i]);
    }
    if (v.is_safe.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "traversability: ";
    if (v.traversability.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.traversability.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<double>::stream(s, true ? std::string() : indent + "    ", v.traversability[i]);
    }
    if (v.traversability.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "untraversable_polygons: ";
    if (v.untraversable_polygons.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.untraversable_polygons.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::geometry_msgs::PolygonStamped_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.untraversable_polygons[i]);
    }
    if (v.untraversable_polygons.empty() || false)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // ELEVATION_MAP_MSGS_MESSAGE_CHECKSAFETYRESPONSE_H
