// Generated by gencpp from file elevation_map_msgs/CheckSafety.msg
// DO NOT EDIT!


#ifndef ELEVATION_MAP_MSGS_MESSAGE_CHECKSAFETY_H
#define ELEVATION_MAP_MSGS_MESSAGE_CHECKSAFETY_H

#include <ros/service_traits.h>


#include <elevation_map_msgs/CheckSafetyRequest.h>
#include <elevation_map_msgs/CheckSafetyResponse.h>


namespace elevation_map_msgs
{

struct CheckSafety
{

typedef CheckSafetyRequest Request;
typedef CheckSafetyResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CheckSafety
} // namespace elevation_map_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::elevation_map_msgs::CheckSafety > {
  static const char* value()
  {
    return "137df6a3ff37546adfad4f1d40e233b4";
  }

  static const char* value(const ::elevation_map_msgs::CheckSafety&) { return value(); }
};

template<>
struct DataType< ::elevation_map_msgs::CheckSafety > {
  static const char* value()
  {
    return "elevation_map_msgs/CheckSafety";
  }

  static const char* value(const ::elevation_map_msgs::CheckSafety&) { return value(); }
};


// service_traits::MD5Sum< ::elevation_map_msgs::CheckSafetyRequest> should match
// service_traits::MD5Sum< ::elevation_map_msgs::CheckSafety >
template<>
struct MD5Sum< ::elevation_map_msgs::CheckSafetyRequest>
{
  static const char* value()
  {
    return MD5Sum< ::elevation_map_msgs::CheckSafety >::value();
  }
  static const char* value(const ::elevation_map_msgs::CheckSafetyRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::elevation_map_msgs::CheckSafetyRequest> should match
// service_traits::DataType< ::elevation_map_msgs::CheckSafety >
template<>
struct DataType< ::elevation_map_msgs::CheckSafetyRequest>
{
  static const char* value()
  {
    return DataType< ::elevation_map_msgs::CheckSafety >::value();
  }
  static const char* value(const ::elevation_map_msgs::CheckSafetyRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::elevation_map_msgs::CheckSafetyResponse> should match
// service_traits::MD5Sum< ::elevation_map_msgs::CheckSafety >
template<>
struct MD5Sum< ::elevation_map_msgs::CheckSafetyResponse>
{
  static const char* value()
  {
    return MD5Sum< ::elevation_map_msgs::CheckSafety >::value();
  }
  static const char* value(const ::elevation_map_msgs::CheckSafetyResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::elevation_map_msgs::CheckSafetyResponse> should match
// service_traits::DataType< ::elevation_map_msgs::CheckSafety >
template<>
struct DataType< ::elevation_map_msgs::CheckSafetyResponse>
{
  static const char* value()
  {
    return DataType< ::elevation_map_msgs::CheckSafety >::value();
  }
  static const char* value(const ::elevation_map_msgs::CheckSafetyResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ELEVATION_MAP_MSGS_MESSAGE_CHECKSAFETY_H
