// Generated by gencpp from file convex_plane_decomposition_msgs/BoundingBox2d.msg
// DO NOT EDIT!


#ifndef CONVEX_PLANE_DECOMPOSITION_MSGS_MESSAGE_BOUNDINGBOX2D_H
#define CONVEX_PLANE_DECOMPOSITION_MSGS_MESSAGE_BOUNDINGBOX2D_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace convex_plane_decomposition_msgs
{
template <class ContainerAllocator>
struct BoundingBox2d_
{
  typedef BoundingBox2d_<ContainerAllocator> Type;

  BoundingBox2d_()
    : min_x(0.0)
    , min_y(0.0)
    , max_x(0.0)
    , max_y(0.0)  {
    }
  BoundingBox2d_(const ContainerAllocator& _alloc)
    : min_x(0.0)
    , min_y(0.0)
    , max_x(0.0)
    , max_y(0.0)  {
  (void)_alloc;
    }



   typedef float _min_x_type;
  _min_x_type min_x;

   typedef float _min_y_type;
  _min_y_type min_y;

   typedef float _max_x_type;
  _max_x_type max_x;

   typedef float _max_y_type;
  _max_y_type max_y;





  typedef boost::shared_ptr< ::convex_plane_decomposition_msgs::BoundingBox2d_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::convex_plane_decomposition_msgs::BoundingBox2d_<ContainerAllocator> const> ConstPtr;

}; // struct BoundingBox2d_

typedef ::convex_plane_decomposition_msgs::BoundingBox2d_<std::allocator<void> > BoundingBox2d;

typedef boost::shared_ptr< ::convex_plane_decomposition_msgs::BoundingBox2d > BoundingBox2dPtr;
typedef boost::shared_ptr< ::convex_plane_decomposition_msgs::BoundingBox2d const> BoundingBox2dConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::convex_plane_decomposition_msgs::BoundingBox2d_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::convex_plane_decomposition_msgs::BoundingBox2d_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::convex_plane_decomposition_msgs::BoundingBox2d_<ContainerAllocator1> & lhs, const ::convex_plane_decomposition_msgs::BoundingBox2d_<ContainerAllocator2> & rhs)
{
  return lhs.min_x == rhs.min_x &&
    lhs.min_y == rhs.min_y &&
    lhs.max_x == rhs.max_x &&
    lhs.max_y == rhs.max_y;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::convex_plane_decomposition_msgs::BoundingBox2d_<ContainerAllocator1> & lhs, const ::convex_plane_decomposition_msgs::BoundingBox2d_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace convex_plane_decomposition_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::convex_plane_decomposition_msgs::BoundingBox2d_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::convex_plane_decomposition_msgs::BoundingBox2d_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::convex_plane_decomposition_msgs::BoundingBox2d_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::convex_plane_decomposition_msgs::BoundingBox2d_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::convex_plane_decomposition_msgs::BoundingBox2d_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::convex_plane_decomposition_msgs::BoundingBox2d_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::convex_plane_decomposition_msgs::BoundingBox2d_<ContainerAllocator> >
{
  static const char* value()
  {
    return "882c57bd03c558cc1c0ff70ad4c5ef0e";
  }

  static const char* value(const ::convex_plane_decomposition_msgs::BoundingBox2d_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x882c57bd03c558ccULL;
  static const uint64_t static_value2 = 0x1c0ff70ad4c5ef0eULL;
};

template<class ContainerAllocator>
struct DataType< ::convex_plane_decomposition_msgs::BoundingBox2d_<ContainerAllocator> >
{
  static const char* value()
  {
    return "convex_plane_decomposition_msgs/BoundingBox2d";
  }

  static const char* value(const ::convex_plane_decomposition_msgs::BoundingBox2d_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::convex_plane_decomposition_msgs::BoundingBox2d_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# 3D, axis-aligned, bounding box\n"
"float32 min_x\n"
"float32 min_y\n"
"float32 max_x\n"
"float32 max_y\n"
;
  }

  static const char* value(const ::convex_plane_decomposition_msgs::BoundingBox2d_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::convex_plane_decomposition_msgs::BoundingBox2d_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.min_x);
      stream.next(m.min_y);
      stream.next(m.max_x);
      stream.next(m.max_y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BoundingBox2d_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::convex_plane_decomposition_msgs::BoundingBox2d_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::convex_plane_decomposition_msgs::BoundingBox2d_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "min_x: ";
    Printer<float>::stream(s, indent + "  ", v.min_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "min_y: ";
    Printer<float>::stream(s, indent + "  ", v.min_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "max_x: ";
    Printer<float>::stream(s, indent + "  ", v.max_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "max_y: ";
    Printer<float>::stream(s, indent + "  ", v.max_y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CONVEX_PLANE_DECOMPOSITION_MSGS_MESSAGE_BOUNDINGBOX2D_H
