// Generated by gencpp from file convex_plane_decomposition_msgs/PlanarRegion.msg
// DO NOT EDIT!


#ifndef CONVEX_PLANE_DECOMPOSITION_MSGS_MESSAGE_PLANARREGION_H
#define CONVEX_PLANE_DECOMPOSITION_MSGS_MESSAGE_PLANARREGION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>
#include <convex_plane_decomposition_msgs/BoundingBox2d.h>
#include <convex_plane_decomposition_msgs/PolygonWithHoles2d.h>
#include <convex_plane_decomposition_msgs/PolygonWithHoles2d.h>

namespace convex_plane_decomposition_msgs
{
template <class ContainerAllocator>
struct PlanarRegion_
{
  typedef PlanarRegion_<ContainerAllocator> Type;

  PlanarRegion_()
    : plane_parameters()
    , bbox2d()
    , boundary()
    , insets()  {
    }
  PlanarRegion_(const ContainerAllocator& _alloc)
    : plane_parameters(_alloc)
    , bbox2d(_alloc)
    , boundary(_alloc)
    , insets(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _plane_parameters_type;
  _plane_parameters_type plane_parameters;

   typedef  ::convex_plane_decomposition_msgs::BoundingBox2d_<ContainerAllocator>  _bbox2d_type;
  _bbox2d_type bbox2d;

   typedef  ::convex_plane_decomposition_msgs::PolygonWithHoles2d_<ContainerAllocator>  _boundary_type;
  _boundary_type boundary;

   typedef std::vector< ::convex_plane_decomposition_msgs::PolygonWithHoles2d_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::convex_plane_decomposition_msgs::PolygonWithHoles2d_<ContainerAllocator> >> _insets_type;
  _insets_type insets;





  typedef boost::shared_ptr< ::convex_plane_decomposition_msgs::PlanarRegion_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::convex_plane_decomposition_msgs::PlanarRegion_<ContainerAllocator> const> ConstPtr;

}; // struct PlanarRegion_

typedef ::convex_plane_decomposition_msgs::PlanarRegion_<std::allocator<void> > PlanarRegion;

typedef boost::shared_ptr< ::convex_plane_decomposition_msgs::PlanarRegion > PlanarRegionPtr;
typedef boost::shared_ptr< ::convex_plane_decomposition_msgs::PlanarRegion const> PlanarRegionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::convex_plane_decomposition_msgs::PlanarRegion_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::convex_plane_decomposition_msgs::PlanarRegion_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::convex_plane_decomposition_msgs::PlanarRegion_<ContainerAllocator1> & lhs, const ::convex_plane_decomposition_msgs::PlanarRegion_<ContainerAllocator2> & rhs)
{
  return lhs.plane_parameters == rhs.plane_parameters &&
    lhs.bbox2d == rhs.bbox2d &&
    lhs.boundary == rhs.boundary &&
    lhs.insets == rhs.insets;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::convex_plane_decomposition_msgs::PlanarRegion_<ContainerAllocator1> & lhs, const ::convex_plane_decomposition_msgs::PlanarRegion_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace convex_plane_decomposition_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::convex_plane_decomposition_msgs::PlanarRegion_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::convex_plane_decomposition_msgs::PlanarRegion_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::convex_plane_decomposition_msgs::PlanarRegion_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::convex_plane_decomposition_msgs::PlanarRegion_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::convex_plane_decomposition_msgs::PlanarRegion_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::convex_plane_decomposition_msgs::PlanarRegion_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::convex_plane_decomposition_msgs::PlanarRegion_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8cff8c52c8273f12e2fd17b9d4a3d417";
  }

  static const char* value(const ::convex_plane_decomposition_msgs::PlanarRegion_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8cff8c52c8273f12ULL;
  static const uint64_t static_value2 = 0xe2fd17b9d4a3d417ULL;
};

template<class ContainerAllocator>
struct DataType< ::convex_plane_decomposition_msgs::PlanarRegion_<ContainerAllocator> >
{
  static const char* value()
  {
    return "convex_plane_decomposition_msgs/PlanarRegion";
  }

  static const char* value(const ::convex_plane_decomposition_msgs::PlanarRegion_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::convex_plane_decomposition_msgs::PlanarRegion_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Pose plane_parameters\n"
"\n"
"BoundingBox2d bbox2d\n"
"\n"
"PolygonWithHoles2d boundary\n"
"\n"
"PolygonWithHoles2d[] insets\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: convex_plane_decomposition_msgs/BoundingBox2d\n"
"# 3D, axis-aligned, bounding box\n"
"float32 min_x\n"
"float32 min_y\n"
"float32 max_x\n"
"float32 max_y\n"
"================================================================================\n"
"MSG: convex_plane_decomposition_msgs/PolygonWithHoles2d\n"
"# Specification of a 2D polygon with holes\n"
"Polygon2d outer_boundary\n"
"Polygon2d[] holes\n"
"================================================================================\n"
"MSG: convex_plane_decomposition_msgs/Polygon2d\n"
"# Specification of a 2D polygon where the first and last points are connected\n"
"Point2d[] points\n"
"================================================================================\n"
"MSG: convex_plane_decomposition_msgs/Point2d\n"
"float32 x\n"
"float32 y\n"
;
  }

  static const char* value(const ::convex_plane_decomposition_msgs::PlanarRegion_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::convex_plane_decomposition_msgs::PlanarRegion_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.plane_parameters);
      stream.next(m.bbox2d);
      stream.next(m.boundary);
      stream.next(m.insets);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PlanarRegion_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::convex_plane_decomposition_msgs::PlanarRegion_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::convex_plane_decomposition_msgs::PlanarRegion_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "plane_parameters: ";
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.plane_parameters);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "bbox2d: ";
    Printer< ::convex_plane_decomposition_msgs::BoundingBox2d_<ContainerAllocator> >::stream(s, indent + "  ", v.bbox2d);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "boundary: ";
    Printer< ::convex_plane_decomposition_msgs::PolygonWithHoles2d_<ContainerAllocator> >::stream(s, indent + "  ", v.boundary);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "insets: ";
    if (v.insets.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.insets.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::convex_plane_decomposition_msgs::PolygonWithHoles2d_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.insets[i]);
    }
    if (v.insets.empty() || false)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // CONVEX_PLANE_DECOMPOSITION_MSGS_MESSAGE_PLANARREGION_H
