// Generated by gencpp from file convex_plane_decomposition_msgs/PlanarTerrain.msg
// DO NOT EDIT!


#ifndef CONVEX_PLANE_DECOMPOSITION_MSGS_MESSAGE_PLANARTERRAIN_H
#define CONVEX_PLANE_DECOMPOSITION_MSGS_MESSAGE_PLANARTERRAIN_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <convex_plane_decomposition_msgs/PlanarRegion.h>
#include <grid_map_msgs/GridMap.h>

namespace convex_plane_decomposition_msgs
{
template <class ContainerAllocator>
struct PlanarTerrain_
{
  typedef PlanarTerrain_<ContainerAllocator> Type;

  PlanarTerrain_()
    : planarRegions()
    , gridmap()  {
    }
  PlanarTerrain_(const ContainerAllocator& _alloc)
    : planarRegions(_alloc)
    , gridmap(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::convex_plane_decomposition_msgs::PlanarRegion_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::convex_plane_decomposition_msgs::PlanarRegion_<ContainerAllocator> >> _planarRegions_type;
  _planarRegions_type planarRegions;

   typedef  ::grid_map_msgs::GridMap_<ContainerAllocator>  _gridmap_type;
  _gridmap_type gridmap;





  typedef boost::shared_ptr< ::convex_plane_decomposition_msgs::PlanarTerrain_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::convex_plane_decomposition_msgs::PlanarTerrain_<ContainerAllocator> const> ConstPtr;

}; // struct PlanarTerrain_

typedef ::convex_plane_decomposition_msgs::PlanarTerrain_<std::allocator<void> > PlanarTerrain;

typedef boost::shared_ptr< ::convex_plane_decomposition_msgs::PlanarTerrain > PlanarTerrainPtr;
typedef boost::shared_ptr< ::convex_plane_decomposition_msgs::PlanarTerrain const> PlanarTerrainConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::convex_plane_decomposition_msgs::PlanarTerrain_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::convex_plane_decomposition_msgs::PlanarTerrain_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::convex_plane_decomposition_msgs::PlanarTerrain_<ContainerAllocator1> & lhs, const ::convex_plane_decomposition_msgs::PlanarTerrain_<ContainerAllocator2> & rhs)
{
  return lhs.planarRegions == rhs.planarRegions &&
    lhs.gridmap == rhs.gridmap;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::convex_plane_decomposition_msgs::PlanarTerrain_<ContainerAllocator1> & lhs, const ::convex_plane_decomposition_msgs::PlanarTerrain_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace convex_plane_decomposition_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::convex_plane_decomposition_msgs::PlanarTerrain_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::convex_plane_decomposition_msgs::PlanarTerrain_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::convex_plane_decomposition_msgs::PlanarTerrain_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::convex_plane_decomposition_msgs::PlanarTerrain_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::convex_plane_decomposition_msgs::PlanarTerrain_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::convex_plane_decomposition_msgs::PlanarTerrain_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::convex_plane_decomposition_msgs::PlanarTerrain_<ContainerAllocator> >
{
  static const char* value()
  {
    return "081e702fce247ef5685dd96b39e3dfd4";
  }

  static const char* value(const ::convex_plane_decomposition_msgs::PlanarTerrain_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x081e702fce247ef5ULL;
  static const uint64_t static_value2 = 0x685dd96b39e3dfd4ULL;
};

template<class ContainerAllocator>
struct DataType< ::convex_plane_decomposition_msgs::PlanarTerrain_<ContainerAllocator> >
{
  static const char* value()
  {
    return "convex_plane_decomposition_msgs/PlanarTerrain";
  }

  static const char* value(const ::convex_plane_decomposition_msgs::PlanarTerrain_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::convex_plane_decomposition_msgs::PlanarTerrain_<ContainerAllocator> >
{
  static const char* value()
  {
    return "PlanarRegion[] planarRegions\n"
"grid_map_msgs/GridMap gridmap\n"
"================================================================================\n"
"MSG: convex_plane_decomposition_msgs/PlanarRegion\n"
"geometry_msgs/Pose plane_parameters\n"
"\n"
"BoundingBox2d bbox2d\n"
"\n"
"PolygonWithHoles2d boundary\n"
"\n"
"PolygonWithHoles2d[] insets\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: convex_plane_decomposition_msgs/BoundingBox2d\n"
"# 3D, axis-aligned, bounding box\n"
"float32 min_x\n"
"float32 min_y\n"
"float32 max_x\n"
"float32 max_y\n"
"================================================================================\n"
"MSG: convex_plane_decomposition_msgs/PolygonWithHoles2d\n"
"# Specification of a 2D polygon with holes\n"
"Polygon2d outer_boundary\n"
"Polygon2d[] holes\n"
"================================================================================\n"
"MSG: convex_plane_decomposition_msgs/Polygon2d\n"
"# Specification of a 2D polygon where the first and last points are connected\n"
"Point2d[] points\n"
"================================================================================\n"
"MSG: convex_plane_decomposition_msgs/Point2d\n"
"float32 x\n"
"float32 y\n"
"================================================================================\n"
"MSG: grid_map_msgs/GridMap\n"
"# Grid map header\n"
"GridMapInfo info\n"
"\n"
"# Grid map layer names.\n"
"string[] layers\n"
"\n"
"# Grid map basic layer names (optional). The basic layers\n"
"# determine which layers from `layers` need to be valid\n"
"# in order for a cell of the grid map to be valid.\n"
"string[] basic_layers\n"
"\n"
"# Grid map data.\n"
"std_msgs/Float32MultiArray[] data\n"
"\n"
"# Row start index (default 0).\n"
"uint16 outer_start_index\n"
"\n"
"# Column start index (default 0).\n"
"uint16 inner_start_index\n"
"\n"
"================================================================================\n"
"MSG: grid_map_msgs/GridMapInfo\n"
"# Header (time and frame)\n"
"Header header\n"
"\n"
"# Resolution of the grid [m/cell].\n"
"float64 resolution\n"
"\n"
"# Length in x-direction [m].\n"
"float64 length_x\n"
"\n"
"# Length in y-direction [m].\n"
"float64 length_y\n"
"\n"
"# Pose of the grid map center in the frame defined in `header` [m].\n"
"geometry_msgs/Pose pose\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Float32MultiArray\n"
"# Please look at the MultiArrayLayout message definition for\n"
"# documentation on all multiarrays.\n"
"\n"
"MultiArrayLayout  layout        # specification of data layout\n"
"float32[]         data          # array of data\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/MultiArrayLayout\n"
"# The multiarray declares a generic multi-dimensional array of a\n"
"# particular data type.  Dimensions are ordered from outer most\n"
"# to inner most.\n"
"\n"
"MultiArrayDimension[] dim # Array of dimension properties\n"
"uint32 data_offset        # padding elements at front of data\n"
"\n"
"# Accessors should ALWAYS be written in terms of dimension stride\n"
"# and specified outer-most dimension first.\n"
"# \n"
"# multiarray(i,j,k) = data[data_offset + dim_stride[1]*i + dim_stride[2]*j + k]\n"
"#\n"
"# A standard, 3-channel 640x480 image with interleaved color channels\n"
"# would be specified as:\n"
"#\n"
"# dim[0].label  = \"height\"\n"
"# dim[0].size   = 480\n"
"# dim[0].stride = 3*640*480 = 921600  (note dim[0] stride is just size of image)\n"
"# dim[1].label  = \"width\"\n"
"# dim[1].size   = 640\n"
"# dim[1].stride = 3*640 = 1920\n"
"# dim[2].label  = \"channel\"\n"
"# dim[2].size   = 3\n"
"# dim[2].stride = 3\n"
"#\n"
"# multiarray(i,j,k) refers to the ith row, jth column, and kth channel.\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/MultiArrayDimension\n"
"string label   # label of given dimension\n"
"uint32 size    # size of given dimension (in type units)\n"
"uint32 stride  # stride of given dimension\n"
;
  }

  static const char* value(const ::convex_plane_decomposition_msgs::PlanarTerrain_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::convex_plane_decomposition_msgs::PlanarTerrain_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.planarRegions);
      stream.next(m.gridmap);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PlanarTerrain_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::convex_plane_decomposition_msgs::PlanarTerrain_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::convex_plane_decomposition_msgs::PlanarTerrain_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "planarRegions: ";
    if (v.planarRegions.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.planarRegions.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::convex_plane_decomposition_msgs::PlanarRegion_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.planarRegions[i]);
    }
    if (v.planarRegions.empty() || false)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "gridmap: ";
    Printer< ::grid_map_msgs::GridMap_<ContainerAllocator> >::stream(s, indent + "  ", v.gridmap);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CONVEX_PLANE_DECOMPOSITION_MSGS_MESSAGE_PLANARTERRAIN_H
