// Generated by gencpp from file convex_plane_decomposition_msgs/Polygon2d.msg
// DO NOT EDIT!


#ifndef CONVEX_PLANE_DECOMPOSITION_MSGS_MESSAGE_POLYGON2D_H
#define CONVEX_PLANE_DECOMPOSITION_MSGS_MESSAGE_POLYGON2D_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <convex_plane_decomposition_msgs/Point2d.h>

namespace convex_plane_decomposition_msgs
{
template <class ContainerAllocator>
struct Polygon2d_
{
  typedef Polygon2d_<ContainerAllocator> Type;

  Polygon2d_()
    : points()  {
    }
  Polygon2d_(const ContainerAllocator& _alloc)
    : points(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::convex_plane_decomposition_msgs::Point2d_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::convex_plane_decomposition_msgs::Point2d_<ContainerAllocator> >> _points_type;
  _points_type points;





  typedef boost::shared_ptr< ::convex_plane_decomposition_msgs::Polygon2d_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::convex_plane_decomposition_msgs::Polygon2d_<ContainerAllocator> const> ConstPtr;

}; // struct Polygon2d_

typedef ::convex_plane_decomposition_msgs::Polygon2d_<std::allocator<void> > Polygon2d;

typedef boost::shared_ptr< ::convex_plane_decomposition_msgs::Polygon2d > Polygon2dPtr;
typedef boost::shared_ptr< ::convex_plane_decomposition_msgs::Polygon2d const> Polygon2dConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::convex_plane_decomposition_msgs::Polygon2d_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::convex_plane_decomposition_msgs::Polygon2d_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::convex_plane_decomposition_msgs::Polygon2d_<ContainerAllocator1> & lhs, const ::convex_plane_decomposition_msgs::Polygon2d_<ContainerAllocator2> & rhs)
{
  return lhs.points == rhs.points;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::convex_plane_decomposition_msgs::Polygon2d_<ContainerAllocator1> & lhs, const ::convex_plane_decomposition_msgs::Polygon2d_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace convex_plane_decomposition_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::convex_plane_decomposition_msgs::Polygon2d_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::convex_plane_decomposition_msgs::Polygon2d_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::convex_plane_decomposition_msgs::Polygon2d_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::convex_plane_decomposition_msgs::Polygon2d_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::convex_plane_decomposition_msgs::Polygon2d_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::convex_plane_decomposition_msgs::Polygon2d_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::convex_plane_decomposition_msgs::Polygon2d_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0083ddac30f807eeef29c66ffedb79c7";
  }

  static const char* value(const ::convex_plane_decomposition_msgs::Polygon2d_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0083ddac30f807eeULL;
  static const uint64_t static_value2 = 0xef29c66ffedb79c7ULL;
};

template<class ContainerAllocator>
struct DataType< ::convex_plane_decomposition_msgs::Polygon2d_<ContainerAllocator> >
{
  static const char* value()
  {
    return "convex_plane_decomposition_msgs/Polygon2d";
  }

  static const char* value(const ::convex_plane_decomposition_msgs::Polygon2d_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::convex_plane_decomposition_msgs::Polygon2d_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Specification of a 2D polygon where the first and last points are connected\n"
"Point2d[] points\n"
"================================================================================\n"
"MSG: convex_plane_decomposition_msgs/Point2d\n"
"float32 x\n"
"float32 y\n"
;
  }

  static const char* value(const ::convex_plane_decomposition_msgs::Polygon2d_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::convex_plane_decomposition_msgs::Polygon2d_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.points);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Polygon2d_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::convex_plane_decomposition_msgs::Polygon2d_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::convex_plane_decomposition_msgs::Polygon2d_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "points: ";
    if (v.points.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.points.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::convex_plane_decomposition_msgs::Point2d_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.points[i]);
    }
    if (v.points.empty() || false)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // CONVEX_PLANE_DECOMPOSITION_MSGS_MESSAGE_POLYGON2D_H
