// Generated by gencpp from file convex_plane_decomposition_msgs/PolygonWithHoles2d.msg
// DO NOT EDIT!


#ifndef CONVEX_PLANE_DECOMPOSITION_MSGS_MESSAGE_POLYGONWITHHOLES2D_H
#define CONVEX_PLANE_DECOMPOSITION_MSGS_MESSAGE_POLYGONWITHHOLES2D_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <convex_plane_decomposition_msgs/Polygon2d.h>
#include <convex_plane_decomposition_msgs/Polygon2d.h>

namespace convex_plane_decomposition_msgs
{
template <class ContainerAllocator>
struct PolygonWithHoles2d_
{
  typedef PolygonWithHoles2d_<ContainerAllocator> Type;

  PolygonWithHoles2d_()
    : outer_boundary()
    , holes()  {
    }
  PolygonWithHoles2d_(const ContainerAllocator& _alloc)
    : outer_boundary(_alloc)
    , holes(_alloc)  {
  (void)_alloc;
    }



   typedef  ::convex_plane_decomposition_msgs::Polygon2d_<ContainerAllocator>  _outer_boundary_type;
  _outer_boundary_type outer_boundary;

   typedef std::vector< ::convex_plane_decomposition_msgs::Polygon2d_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::convex_plane_decomposition_msgs::Polygon2d_<ContainerAllocator> >> _holes_type;
  _holes_type holes;





  typedef boost::shared_ptr< ::convex_plane_decomposition_msgs::PolygonWithHoles2d_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::convex_plane_decomposition_msgs::PolygonWithHoles2d_<ContainerAllocator> const> ConstPtr;

}; // struct PolygonWithHoles2d_

typedef ::convex_plane_decomposition_msgs::PolygonWithHoles2d_<std::allocator<void> > PolygonWithHoles2d;

typedef boost::shared_ptr< ::convex_plane_decomposition_msgs::PolygonWithHoles2d > PolygonWithHoles2dPtr;
typedef boost::shared_ptr< ::convex_plane_decomposition_msgs::PolygonWithHoles2d const> PolygonWithHoles2dConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::convex_plane_decomposition_msgs::PolygonWithHoles2d_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::convex_plane_decomposition_msgs::PolygonWithHoles2d_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::convex_plane_decomposition_msgs::PolygonWithHoles2d_<ContainerAllocator1> & lhs, const ::convex_plane_decomposition_msgs::PolygonWithHoles2d_<ContainerAllocator2> & rhs)
{
  return lhs.outer_boundary == rhs.outer_boundary &&
    lhs.holes == rhs.holes;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::convex_plane_decomposition_msgs::PolygonWithHoles2d_<ContainerAllocator1> & lhs, const ::convex_plane_decomposition_msgs::PolygonWithHoles2d_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace convex_plane_decomposition_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::convex_plane_decomposition_msgs::PolygonWithHoles2d_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::convex_plane_decomposition_msgs::PolygonWithHoles2d_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::convex_plane_decomposition_msgs::PolygonWithHoles2d_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::convex_plane_decomposition_msgs::PolygonWithHoles2d_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::convex_plane_decomposition_msgs::PolygonWithHoles2d_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::convex_plane_decomposition_msgs::PolygonWithHoles2d_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::convex_plane_decomposition_msgs::PolygonWithHoles2d_<ContainerAllocator> >
{
  static const char* value()
  {
    return "62e09666eefc245f9ca3347875cb36cc";
  }

  static const char* value(const ::convex_plane_decomposition_msgs::PolygonWithHoles2d_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x62e09666eefc245fULL;
  static const uint64_t static_value2 = 0x9ca3347875cb36ccULL;
};

template<class ContainerAllocator>
struct DataType< ::convex_plane_decomposition_msgs::PolygonWithHoles2d_<ContainerAllocator> >
{
  static const char* value()
  {
    return "convex_plane_decomposition_msgs/PolygonWithHoles2d";
  }

  static const char* value(const ::convex_plane_decomposition_msgs::PolygonWithHoles2d_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::convex_plane_decomposition_msgs::PolygonWithHoles2d_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Specification of a 2D polygon with holes\n"
"Polygon2d outer_boundary\n"
"Polygon2d[] holes\n"
"================================================================================\n"
"MSG: convex_plane_decomposition_msgs/Polygon2d\n"
"# Specification of a 2D polygon where the first and last points are connected\n"
"Point2d[] points\n"
"================================================================================\n"
"MSG: convex_plane_decomposition_msgs/Point2d\n"
"float32 x\n"
"float32 y\n"
;
  }

  static const char* value(const ::convex_plane_decomposition_msgs::PolygonWithHoles2d_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::convex_plane_decomposition_msgs::PolygonWithHoles2d_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.outer_boundary);
      stream.next(m.holes);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PolygonWithHoles2d_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::convex_plane_decomposition_msgs::PolygonWithHoles2d_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::convex_plane_decomposition_msgs::PolygonWithHoles2d_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "outer_boundary: ";
    Printer< ::convex_plane_decomposition_msgs::Polygon2d_<ContainerAllocator> >::stream(s, indent + "  ", v.outer_boundary);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "holes: ";
    if (v.holes.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.holes.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::convex_plane_decomposition_msgs::Polygon2d_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.holes[i]);
    }
    if (v.holes.empty() || false)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // CONVEX_PLANE_DECOMPOSITION_MSGS_MESSAGE_POLYGONWITHHOLES2D_H
